[package]
name = "chillup"
version = "0.1.0"
authors = ["Cokemonkey11"]
edition = "2018"
description = "A dependency search tool for wurstlang libraries"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/Cokemonkey11/chillup"
repository = "https://github.com/Cokemonkey11/wurstdoktor"
readme = "README.md"
keywords = ["wurst", "wurstlang", "dependencies", "search"]
categories = ["command-line-utilities", "development-tools", "web-programming::http-client"]

[dependencies]
failure = "0.1.5"
paw     = "1.0.0"
reqwest = "0.9.19"
select  = "0.4.3"
